#!/usr/bin/env bash
#
# setup-autopull.sh — make the laptop fully "set & forget".
#
# Installs a LaunchAgent that, every 15 minutes AND on every login/reboot:
#   1. git pull --rebase the job-finder repo (picks up pushes automatically)
#   2. makes sure the self-hosted runner is alive; restarts it if it died
#
# Combined with the runner service (setup-runner.sh) and no-sleep, this makes the
# laptop run everything dynamically with zero manual steps.
#
# USAGE (run from inside the job-finder repo folder on the laptop):
#   bash setup-autopull.sh
#
set -euo pipefail

# --- locate things dynamically (no hardcoded paths) ---
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && git rev-parse --show-toplevel 2>/dev/null || pwd)"
RUNNER_DIR="$HOME/gh-runner"
LABEL="com.bobur.jobfinder.autopull"
PLIST="$HOME/Library/LaunchAgents/${LABEL}.plist"
WORKER="$HOME/.jobfinder-autopull.sh"
LOG="$HOME/.jobfinder-autopull.log"

echo "➡️  repo:   $REPO_DIR"
echo "➡️  runner: $RUNNER_DIR"

# --- 1. write the worker script the agent runs every 15 min ---
cat > "$WORKER" <<WORKEOF
#!/usr/bin/env bash
# auto-generated by setup-autopull.sh — do not edit by hand
exec >> "$LOG" 2>&1
echo "----- \$(date) -----"

# (a) pull latest code
if [ -d "$REPO_DIR/.git" ]; then
  cd "$REPO_DIR"
  git pull --rebase --autostash || echo "git pull failed (will retry next cycle)"
fi

# (b) runner watchdog — restart if the listener is not running.
#     The runner SERVICE (svc.sh) already auto-restarts via launchd; this is a
#     no-sudo safety net that relaunches run.sh in the background if it's truly down.
if ! pgrep -f Runner.Listener >/dev/null 2>&1; then
  echo "runner DOWN → relaunching (nohup, no sudo)"
  if [ -x "$RUNNER_DIR/run.sh" ]; then
    (cd "$RUNNER_DIR" && nohup ./run.sh >> "$HOME/.jobfinder-runner.log" 2>&1 &)
  fi
else
  echo "runner OK"
fi
WORKEOF
chmod +x "$WORKER"

# --- 2. write the LaunchAgent plist (runs at load + every 900s) ---
mkdir -p "$HOME/Library/LaunchAgents"
cat > "$PLIST" <<PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${WORKER}</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>StartInterval</key><integer>900</integer>
  <key>StandardOutPath</key><string>${LOG}</string>
  <key>StandardErrorPath</key><string>${LOG}</string>
</dict>
</plist>
PLISTEOF

# --- 3. (re)load the agent ---
launchctl unload "$PLIST" 2>/dev/null || true
launchctl load "$PLIST"

# --- 4. disable Mac sleep so the runner stays online 24/7 ---
echo "➡️  Disabling sleep (needs your Mac password)..."
if sudo pmset -a sleep 0 disablesleep 1 2>/dev/null; then
  echo "   ✅ sleep disabled (sleep 0, disablesleep 1)"
else
  echo "   ⚠️ couldn't set pmset automatically — run this once manually:"
  echo "        sudo pmset -a sleep 0 disablesleep 1"
fi

echo ""
echo "✅ Auto-pull + runner-watchdog + no-sleep installed."
echo "   • git pull runs automatically every 15 min + on every login/reboot."
echo "   • if the runner ever dies, it is restarted automatically."
echo "   • Mac will not sleep (runner stays online 24/7)."
echo "   • log: $LOG"
echo "   • check it's loaded:  launchctl list | grep ${LABEL}"
echo "   • run it once now:     bash $WORKER && tail $LOG"
